# Simple workflow for checking test coverage threshold
name: Check Test Coverage

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent
concurrency:
  group: "cover"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1.4.1

      - name: Run tests
        run: deno task cover
